language: perl
perl:
- '5.16'
install:
- cpanm --notest --installdeps .
before_install:
# install dwca validator
- sudo apt-get update
- sudo apt-get install cpanminus maven git java-common
- git clone https://github.com/gbif/dwca-validator.git $HOME/dwca-validator
- cd $HOME/dwca-validator && mvn clean install
- echo "alias dwca-validator='java -jar $HOME/dwca-validator/dwca-validator-lib/target/dwca-validator.jar'" >> $HOME/.bashrc
# send encrypted google key
- openssl aes-256-cbc -K $encrypted_924227d5d0a5_key -iv $encrypted_924227d5d0a5_iv
  -in google_spreadsheet.session.enc -out google_spreadsheet.session -d
